  php71:
      build: ./build/php71
      privileged: true
      ports:
        - "9071:9000"
      volumes:
        - ${APP_PATH}work/wwwroot/:/etc/nginx/html/
        - ${APP_PATH}work/php71/php.ini:/usr/local/etc/php/php.ini
        - ${APP_PATH}work/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf

  php56:
      build: ./build/php56
      privileged: true
      ports:
        - "9056:9000"
      volumes:
        - ${APP_PATH}work/wwwroot/:/etc/nginx/html/
        - ${APP_PATH}work/php56/php.ini:/usr/local/etc/php/php.ini
        - ${APP_PATH}work/php56/php-fpm.conf:/usr/local/etc/php-fpm.conf
  nginx:
      build: ./build/nginx
      privileged: true
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php71"
        - "php56"
      volumes:
        - ${APP_PATH}work/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${APP_PATH}work/nginx/conf.d/:/etc/nginx/conf.d/
        - ${APP_PATH}work/wwwroot/:/etc/nginx/html/
        - ${APP_PATH}work/nginx/log/:/var/log/nginx/